name: mmth_flutter
description: MMTH Project for Mitsubishi's Motors

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

analyzer:
  enable-experiment:
    - non-nullable

environment:
  sdk: ">=2.11.0-213.1.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.8.1
  carousel_slider: ^2.2.1
  url_launcher: ^5.5.2
  scrollable_positioned_list: ^0.1.7
  google_fonts: ^1.1.0
  intl: ^0.16.1
  flutter_rating_bar: ^3.2.0+1
  cupertino_icons: ^1.0.0
  fancy_bottom_navigation: ^0.3.2
  settings_ui: ^0.6.0
  shared_preferences: ^0.5.12+4
  animated_text_kit: ^3.1.2
  http: ^0.12.0+2
  scoped_model: ^1.0.1
  image_picker: ^0.6.7+7
  cached_network_image: ^2.3.1
  socket_io_client: ^0.9.12
  flutter_local_notifications: ^1.2.1
  web_socket_channel: ^1.1.0
  workmanager: ^0.2.0
  flutter_slidable: ^0.5.7
  charts_flutter: ^0.9.0
  dash_chat: ^1.1.15
  fl_chart: ^0.20.1
  responsive_framework: ^0.0.15
  webview_flutter: ^1.0.7
  universal_html: ^1.2.3
  dropdown_search: ^0.4.9
  passcode_screen: ^1.2.2+1
  flutter_app_lock: ^1.4.0+1
  video_player: ^2.0.2
  fluttertoast: ^7.0.2
  photo_view: ^0.10.2
  universal_io: ^1.0.2
  xml2json: ^5.0.0
  loading: ^1.0.2
  firebase_core:
  firebase_messaging:
  firebase_storage:
  firebase_auth:
  firebase_analytics:
  google_sign_in: ^4.5.3
  cloud_firestore:





dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/pro-background.png
    - assets/img/onboard-background.png
    - assets/img/logo-android.png
    - assets/img/logo-ios.png
    - assets/img/logo-argon.png
    - assets/img/profile-screen-avatar.jpg
    - assets/img/profile-screen-bg.png
    - assets/img/register-bg.png
    - assets/img/chat-avatar.jpeg
    - assets/img/argon-logo.png
    - assets/img/argon-logo-onboarding.png
    - assets/img/mitsu_logo.png
    - assets/img/supportIcon.png
    - assets/img/
    - assets/data/user_data.json
    - assets/data/lop.json
    - assets/data/dealer.json
    - assets/data/random_data.json
    - assets/img/settings.png
    - assets/img/mitsu_logo_login.png
    - assets/img/incident.png
    - assets/img/mitsu_logo_login_notext.png
    - assets/images/flutter_logo_text.png
    - assets/images/icon_search_64x.png
    - assets/images/icon_twitter_64x.png
    - assets/images/icon_youtube_64x.png
    - assets/images/icon_github_64x.png
    - assets/images/
    - assets/img/ico/
    - assets/img/ico/manifest.json
    - images/img_not_available.jpeg
    - images/mimi1.gif
    - images/mimi2.gif
    - images/mimi3.gif
    - images/mimi4.gif
    - images/mimi5.gif
    - images/mimi6.gif
    - images/mimi7.gif
    - images/mimi8.gif
    - images/mimi9.gif

  fonts:
    - family: Sarabun
      fonts:
        - asset: assets/fonts/Sarabun-Regular.ttf
        - asset: assets/fonts/Sarabun-Light.ttf
          weight: 200
        - asset: assets/fonts/Sarabun-Bold.ttf
          weight: 600

